/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BmiCalculatorRouteImport } from './routes/bmi-calculator'
import { Route as IndexRouteImport } from './routes/index'

const BmiCalculatorRoute = BmiCalculatorRouteImport.update({
  id: '/bmi-calculator',
  path: '/bmi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bmi-calculator': typeof BmiCalculatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bmi-calculator': typeof BmiCalculatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bmi-calculator': typeof BmiCalculatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bmi-calculator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bmi-calculator'
  id: '__root__' | '/' | '/bmi-calculator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BmiCalculatorRoute: typeof BmiCalculatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bmi-calculator': {
      id: '/bmi-calculator'
      path: '/bmi-calculator'
      fullPath: '/bmi-calculator'
      preLoaderRoute: typeof BmiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BmiCalculatorRoute: BmiCalculatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
