/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BMICalcRouteImport } from './routes/BMICalc'
import { Route as IndexRouteImport } from './routes/index'

const BMICalcRoute = BMICalcRouteImport.update({
  id: '/BMICalc',
  path: '/BMICalc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/BMICalc': typeof BMICalcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/BMICalc': typeof BMICalcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/BMICalc': typeof BMICalcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/BMICalc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/BMICalc'
  id: '__root__' | '/' | '/BMICalc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BMICalcRoute: typeof BMICalcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/BMICalc': {
      id: '/BMICalc'
      path: '/BMICalc'
      fullPath: '/BMICalc'
      preLoaderRoute: typeof BMICalcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BMICalcRoute: BMICalcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
